-- ================================================================
-- AI WEBSITE BUILDER DATABASE SCHEMA
-- PostgreSQL VERSION
-- MVP 1.0
-- ================================================================

-- ================================================================
-- TABLE: users
-- ================================================================

CREATE TABLE users (
    id UUID PRIMARY KEY,

    email VARCHAR(255) NOT NULL UNIQUE,

    username VARCHAR(100) NOT NULL UNIQUE,

    password_hash VARCHAR(255) NOT NULL,

    full_name VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ================================================================
-- TABLE: projects
-- ================================================================

CREATE TABLE projects (
    id UUID PRIMARY KEY,

    user_id UUID NOT NULL,

    name VARCHAR(255) NOT NULL,

    description TEXT,

    status VARCHAR(50) NOT NULL DEFAULT 'draft',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_projects_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_projects_user_id
    ON projects(user_id);

-- ================================================================
-- TABLE: prompts
-- ================================================================

CREATE TABLE prompts (
    id UUID PRIMARY KEY,

    project_id UUID NOT NULL,

    user_id UUID NOT NULL,

    prompt_text TEXT NOT NULL,

    prompt_type VARCHAR(50) NOT NULL DEFAULT 'website',

    status VARCHAR(50) NOT NULL DEFAULT 'pending',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_prompts_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_prompts_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_prompts_project_id
    ON prompts(project_id);

CREATE INDEX idx_prompts_user_id
    ON prompts(user_id);

-- ================================================================
-- TABLE: uploads
-- ================================================================

CREATE TABLE uploads (
    id UUID PRIMARY KEY,

    user_id UUID NOT NULL,

    project_id UUID,

    filename VARCHAR(255) NOT NULL,

    file_path VARCHAR(500) NOT NULL,

    file_type VARCHAR(50),

    file_size BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_uploads_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_uploads_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_uploads_project_id
    ON uploads(project_id);

CREATE INDEX idx_uploads_user_id
    ON uploads(user_id);

-- ================================================================
-- TABLE: generated_websites
-- ================================================================

CREATE TABLE generated_websites (
    id UUID PRIMARY KEY,

    project_id UUID NOT NULL,

    prompt_id UUID,

    user_id UUID NOT NULL,

    website_json JSONB NOT NULL,

    version INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_generated_websites_project
        FOREIGN KEY (project_id)
        REFERENCES projects(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_generated_websites_prompt
        FOREIGN KEY (prompt_id)
        REFERENCES prompts(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_generated_websites_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_generated_websites_project_id
    ON generated_websites(project_id);

CREATE INDEX idx_generated_websites_user_id
    ON generated_websites(user_id);

-- ================================================================
-- SAMPLE DATA
-- ================================================================

-- Sample user
-- Password: demo123
-- NOTE: Replace this hash with a hash generated by your application
-- if you actually use this account.

INSERT INTO users (
    id,
    email,
    username,
    password_hash,
    full_name
)
VALUES (
    '550e8400-e29b-41d4-a716-446655440000',
    'demo@example.com',
    'demo_user',
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqVk.7Jqha',
    'Demo User'
);

-- Sample project

INSERT INTO projects (
    id,
    user_id,
    name,
    description,
    status
)
VALUES (
    '660e8400-e29b-41d4-a716-446655440001',
    '550e8400-e29b-41d4-a716-446655440000',
    'My First Website',
    'AI generated website project',
    'draft'
);

-- ================================================================
-- OPTIONAL: AUTOMATIC updated_at
-- PostgreSQL does not support MySQL's
-- ON UPDATE CURRENT_TIMESTAMP.
-- ================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ================================================================
-- VERIFY TABLES
-- ================================================================

-- Run:
-- \dt

-- Check table structure:
-- \d users
-- \d projects
-- \d prompts
-- \d uploads
-- \d generated_websites